# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAlgorithms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=200, verbose_name='Name')),
                ('docker_image', models.CharField(max_length=200, verbose_name='Docker Image')),
            ],
        ),
    ]
