# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20170126_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningcontainer',
            name='node_id',
            field=models.CharField(max_length=200, verbose_name='Node ID'),
        ),
    ]
