# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_availablealgorithms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningcontainer',
            old_name='visitor_id',
            new_name='node_id',
        ),
    ]
